services:
  postgres:
    image: postgres
    container_name: postgres-container
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    env_file:
      - .env
    ports:
      - "5050:80"

  postgres_test:
    image: postgres
    container_name: postgres-test-container
    env_file:
      - .env.test
    ports:
      - "5433:5432"
