services:
  postgres:
    image: postgres
    container_name: postgres-container
    env_file:
      - .env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    env_file:
      - .env
    ports:
      - "5050:80"
